Repository twizzler-operating-system/twizzler, pull requests merged in 2022-08, with the labels that each got.

#81 Initial work implementing Twizzler driver abstractions.
  Cargo.lock
  src/bin/devmgr/Cargo.toml
  src/bin/devmgr/src/main.rs
  src/bin/devmgr/src/nvme_test.rs
  src/bin/init/Cargo.toml
  src/bin/init/src/main.rs
  src/kernel/Cargo.toml
  src/kernel/src/arch/amd64/interrupt.rs
  src/kernel/src/device.rs
  src/kernel/src/interrupt.rs
  src/kernel/src/machine/pc/pcie.rs
  src/lib/twizzler-abi/src/device/bus/pcie.rs
  src/lib/twizzler-abi/src/device/mod.rs
  src/lib/twizzler-abi/src/kso.rs
  src/lib/twizzler-abi/src/vcell.rs
  src/lib/twizzler-async/src/async_source.rs
  src/lib/twizzler-async/src/reactor.rs
  src/lib/twizzler-driver/Cargo.toml
  src/lib/twizzler-driver/src/bus/pcie.rs
  src/lib/twizzler-driver/src/controller.rs
  src/lib/twizzler-driver/src/device.rs
  src/lib/twizzler-driver/src/device/children.rs
  src/lib/twizzler-driver/src/device/events.rs
  src/lib/twizzler-driver/src/device/info.rs
  src/lib/twizzler-driver/src/device/mmio.rs
  src/lib/twizzler-driver/src/device/mod.rs
  src/lib/twizzler-driver/src/dma.rs
  src/lib/twizzler-driver/src/lib.rs
  src/lib/twizzler-driver/src/request/async_ids.rs
  src/lib/twizzler-driver/src/request/inflight.rs
  src/lib/twizzler-driver/src/request/mod.rs
  src/lib/twizzler-driver/src/request/requester.rs
  src/lib/twizzler-driver/src/request/response_info.rs
  src/lib/twizzler-driver/src/request/submit.rs
  src/lib/twizzler-driver/src/request/summary.rs
  tools/xtask/src/qemu.rs
Labels: enhancement

#85 Initial API stubs of DMA functions for RFC#0006
  Cargo.lock
  src/lib/twizzler-driver/Cargo.toml
  src/lib/twizzler-driver/src/controller.rs
  src/lib/twizzler-driver/src/device/mod.rs
  src/lib/twizzler-driver/src/dma.rs
  src/lib/twizzler-driver/src/dma/mod.rs
  src/lib/twizzler-driver/src/dma/object.rs
  src/lib/twizzler-driver/src/dma/pin.rs
  src/lib/twizzler-driver/src/dma/pool.rs
  src/lib/twizzler-driver/src/dma/region.rs
  src/lib/twizzler-driver/src/lib.rs
Labels: enhancement

#86 Kernel object page pinning and DmaObject + DmaRegion implementation.
  src/bin/init/src/main.rs
  src/kernel/src/device.rs
  src/kernel/src/idcounter.rs
  src/kernel/src/obj/mod.rs
  src/kernel/src/syscall/mod.rs
  src/lib/twizzler-abi/src/kso.rs
  src/lib/twizzler-abi/src/syscall/kaction.rs
  src/lib/twizzler-driver/src/arch/mod.rs
  src/lib/twizzler-driver/src/arch/x86.rs
  src/lib/twizzler-driver/src/device/children.rs
  src/lib/twizzler-driver/src/device/mod.rs
  src/lib/twizzler-driver/src/dma/mod.rs
  src/lib/twizzler-driver/src/dma/object.rs
  src/lib/twizzler-driver/src/dma/pin.rs
  src/lib/twizzler-driver/src/dma/pool.rs
  src/lib/twizzler-driver/src/dma/region.rs
  src/lib/twizzler-driver/src/lib.rs
  src/lib/twizzler-object/src/object.rs
Labels: enhancement

#87 First pass at dev guide for DMA
  doc/src/DMA.md
  doc/src/SUMMARY.md
Labels: documentation

#88 Implement functions for packing and unpacking kaction arguments for pinned pages.
  src/kernel/src/device.rs
  src/lib/twizzler-abi/src/kso.rs
  src/lib/twizzler-driver/src/dma/region.rs
Labels: enhancement

#89 Implement DMA pool functions.
  src/lib/twizzler-driver/src/arch/x86.rs
  src/lib/twizzler-driver/src/dma/mod.rs
  src/lib/twizzler-driver/src/dma/object.rs
  src/lib/twizzler-driver/src/dma/pool.rs
  src/lib/twizzler-driver/src/dma/region.rs
Labels: enhancement

#90 Add note on DMA pools to DMA docs.
  doc/src/DMA.md
Labels: documentation

#92 Implement freelist compaction for DMA pool.
  src/lib/twizzler-driver/src/dma/pool.rs
Labels: enhancement

#78 Time APIs for User and Kernel
  src/kernel/src/arch/amd64/mod.rs
  src/kernel/src/arch/amd64/processor.rs
  src/kernel/src/arch/amd64/tsc.rs
  src/kernel/src/clock.rs
  src/kernel/src/machine/mod.rs
  src/kernel/src/machine/time.rs
  src/kernel/src/main.rs
  src/kernel/src/syscall/mod.rs
  src/kernel/src/time.rs
  src/lib/twizzler-abi/src/syscall/mod.rs
  src/lib/twizzler-abi/src/syscall/time.rs
  src/lib/twizzler-abi/src/syscall/time/clock.rs
  src/lib/twizzler-abi/src/syscall/time/mod.rs
  src/lib/twizzler-abi/src/syscall/time/time.rs
  src/lib/twizzler-abi/src/syscall/time/units.rs
  src/lib/twizzler-abi/src/time.rs
  tools/xtask/src/qemu.rs
Labels: enhancement, kernel, abi

#94 Add additional API documentation to the twizzler-driver crate.
  src/lib/twizzler-driver/src/bus/mod.rs
  src/lib/twizzler-driver/src/bus/pcie.rs
  src/lib/twizzler-driver/src/controller.rs
  src/lib/twizzler-driver/src/device/children.rs
  src/lib/twizzler-driver/src/device/events.rs
  src/lib/twizzler-driver/src/device/info.rs
  src/lib/twizzler-driver/src/device/mmio.rs
  src/lib/twizzler-driver/src/device/mod.rs
  src/lib/twizzler-driver/src/lib.rs
  src/lib/twizzler-driver/src/request/async_ids.rs
  src/lib/twizzler-driver/src/request/inflight.rs
  src/lib/twizzler-driver/src/request/mod.rs
  src/lib/twizzler-driver/src/request/requester.rs
  src/lib/twizzler-driver/src/request/response_info.rs
  src/lib/twizzler-driver/src/request/submit.rs
  src/lib/twizzler-driver/src/request/summary.rs
Labels: documentation
